version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5435:5432
    volumes:
      - /home/ubuntu/projects/hrwebapplication/upload:/home/ubuntu/projects/hrwebapplication/upload
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres



